name: Build and Deploy ASP.NET Core MVC to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # ← अपनी .NET version डालें

      - name: Restore dependencies
        run: dotnet restore DemoWebApplication/DemoWebApplication.csproj

      - name: Build
        run: dotnet build DemoWebApplication/DemoWebApplication.csproj --configuration Release

      - name: Publish
        run: dotnet publish DemoWebApplication/DemoWebApplication.csproj -c
